title: "Serial Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Service mode: signing or admin
mode: signing

# Path to the assets (${docRoot}/static)
docRoot: "."

# Backend database details
driver: "postgres"
datasource: "dbname=serialvault sslmode=disable"

# Signing Key Store
#keystore: "filesystem"
#keystorePath: "./keystore"

# For Database
keystore: "database"
# CHANGEME: This keystoreSecret value is only a sample. Please provide another custom generated one
keystoreSecret: "secret code to encrypt the auth-key hash"

# For TPM 2.0
#keystore: "tpm2.0"
#keystorePath: "./keystore"
#keystoreSecret: "this needs to be 32 bytes long!!"

# 32 bytes long key to protect server from cross site request forgery attacks
# CHANGEME: This csrfAuthKey value is only a sample. Please provide another custom generated one
csrfAuthKey: "2E6ZYnVYUfDLRLV/ne8M6v1jyB/376BL9ORnN3Kgb04uSFalr2ygReVsOt0PaGEIRuID10TePBje5xdjIOEjQQ=="

# Return URL of the service (needed for OpenID)
urlHost: "serial-vault:8081"
urlScheme: http

# Enable user authentication using Ubuntu SSO
enableUserAuth: True

# Key needed for USSO. 
# CHANGEME: This jwtSecret is only a sample. Please provide another custom generated value
jwtSecret: "regoo7Koh7Jeij2hig0Kaeg1ait0eeghaew7Ogheey4pheejohyaongoh6thoBeech6ahc9yaWo3ef4Dah3heeguoqu0oa9A"

